<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CitySeeder extends Seeder
{
    public $cities = [
        ["name"=> "Saint-Mathieu-de-Laprairie", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Amos", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Belleterre", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Duparquet", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "La Sarre", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Macamic", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Malartic", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Rouyn-Noranda", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "La Sarre", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Senneterre", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Témiscaming", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Val-d'Or", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Ville-Marie", "region_id" => "Abitibi-Témiscamingue"],
        ["name"=> "Kirkland", "region_id" => "Agglomération de Montréal"],
        ["name"=> "Westmount", "region_id" => "Agglomération de Montréal"],
        ["name"=> "Amqui", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Cabano", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Causapscal", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Dégelis", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "La Pocatière", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Mont-Joli", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Notre-Dame-du-Lac", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "La Pocatière", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Pohénégamook", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Rimouski", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Rivière-du-Loup", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Saint-Pascal", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Trois-Pistoles", "region_id" => "Bas-Saint-Laurent"],
        ["name"=> "Baie-Saint-Paul", "region_id" => "Capitale-Nationale"],
        ["name"=> "Beaupré", "region_id" => "Capitale-Nationale"],
        ["name"=> "Cap-Santé", "region_id" => "Capitale-Nationale"],
        ["name"=> "Château-Richer", "region_id" => "Capitale-Nationale"],
        ["name"=> "Clermont", "region_id" => "Capitale-Nationale"],
        ["name"=> "Donnacona", "region_id" => "Capitale-Nationale"],
        ["name"=> "Fossambault-sur-le-Lac", "region_id" => "Capitale-Nationale"],
        ["name"=> "Lac-Delage", "region_id" => "Capitale-Nationale"],
        ["name"=> "Lac-Saint-Joseph", "region_id" => "Capitale-Nationale"],
        ["name"=> "Lac-Sergent", "region_id" => "Capitale-Nationale"],
        ["name"=> "L'Ancienne-Lorette", "region_id" => "Capitale-Nationale"],
        ["name"=> "La Malbaie", "region_id" => "Capitale-Nationale"],
        ["name"=> "Neuville", "region_id" => "Capitale-Nationale"],
        ["name"=> "Pont-Rouge", "region_id" => "Capitale-Nationale"],
        ["name"=> "Portneuf", "region_id" => "Capitale-Nationale"],
        ["name"=> "Québec", "region_id" => "Capitale-Nationale"],
        ["name"=> "Sainte-Anne-de-Beaupré", "region_id" => "Capitale-Nationale"],
        ["name"=> "Saint-Augustin-de-Desmaures", "region_id" => "Capitale-Nationale"],
        ["name"=> "Saint-Basile", "region_id" => "Capitale-Nationale"],
        ["name"=> "Sainte-Catherine-de-la-Jacques-Cartier", "region_id" => "Capitale-Nationale"],
        ["name"=> "Saint-Marc-des-Carrières", "region_id" => "Capitale-Nationale"],
        ["name"=> "Saint-Raymond", "region_id" => "Capitale-Nationale"],
        ["name"=> "Bécancour", "region_id" => "Centre-du-Québec"],
        ["name"=> "Danville", "region_id" => "Centre-du-Québec"],
        ["name"=> "Daveluyville", "region_id" => "Centre-du-Québec"],
        ["name"=> "Drummondville", "region_id" => "Centre-du-Québec"],
        ["name"=> "Nicolet", "region_id" => "Centre-du-Québec"],
        ["name"=> "Plessisville", "region_id" => "Centre-du-Québec"],
        ["name"=> "Princeville", "region_id" => "Centre-du-Québec"],
        ["name"=> "Victoriaville", "region_id" => "Centre-du-Québec"],
        ["name"=> "Warwick", "region_id" => "Centre-du-Québec"],
        ["name"=> "Beauceville","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Disraeli","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Lévis","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Montmagny","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Saint-Georges","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Saint-Joseph-de-Beauce","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Sainte-Marie","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Saint-Pamphile","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Thetford Mines","region_id" => "Chaudière-Appalaches"],
        ["name"=> "Baie-Comeau", "region_id" => "Côte-Nord"],
        ["name"=> "Fermont", "region_id" => "Côte-Nord"],
        ["name"=> "Forestville", "region_id" => "Côte-Nord"],
        ["name"=> "Port-Cartier", "region_id" => "Côte-Nord"],
        ["name"=> "Sept-Îles", "region_id" => "Côte-Nord"],
        ["name"=> "Asbestos", "region_id" => "Estrie"],
        ["name"=> "Bedford", "region_id" => "Estrie"],
        ["name"=> "Bromont", "region_id" => "Estrie"],
        ["name"=> "Coaticook", "region_id" => "Estrie"],
        ["name"=> "Cookshire-Eaton", "region_id" => "Estrie"],
        ["name"=> "Delson", "region_id" => "Estrie"],
        ["name"=> "East Angus", "region_id" => "Estrie"],
        ["name"=> "Kingsey Falls", "region_id" => "Estrie"],
        ["name"=> "Lac-Mégantic", "region_id" => "Estrie"],
        ["name"=> "Magog", "region_id" => "Estrie"],
        ["name"=> "Richmond", "region_id" => "Estrie"],
        ["name"=> "Scotstown", "region_id" => "Estrie"],
        ["name"=> "Sherbrooke", "region_id" => "Estrie"],
        ["name"=> "Stanstead", "region_id" => "Estrie"],
        ["name"=> "Valcourt", "region_id" => "Estrie"],
        ["name"=> "Waterloo", "region_id" => "Estrie"],
        ["name"=> "Waterville", "region_id" => "Estrie"],
        ["name"=> "Windsor", "region_id" => "Estrie"],
        ["name"=> "Bonaventure", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Cap-Chat", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Carleton-sur-Mer", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Chandler", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Gaspé", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Grande-Rivière", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Matane", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Métis-sur-Mer", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Murdochville", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "New Richmond", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Paspébiac", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Percé", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Sainte-Anne-des-Monts", "region_id" => "Gaspésie–Îles-de-la-Madeleine"],
        ["name"=> "Berthierville", "region_id" => "Lanaudière"],
        ["name"=> "Charlemagne", "region_id" => "Laurentides"],
        ["name"=> "Joliette", "region_id" => "Laurentides"],
        ["name"=> "L'Assomption", "region_id" => "Laurentides"],
        ["name"=> "L'Épiphanie", "region_id" => "Laurentides"],
        ["name"=> "Lavaltrie", "region_id" => "Laurentides"],
        ["name"=> "Mascouche", "region_id" => "Laurentides"],
        ["name"=> "Notre-Dame-des-Prairies", "region_id" => "Laurentides"],
        ["name"=> "Repentigny", "region_id" => "Laurentides"],
        ["name"=> "Saint-Gabriel", "region_id" => "Laurentides"],
        ["name"=> "Saint-Lin-Laurentides", "region_id" => "Laurentides"],
        ["name"=> "Terrebonne", "region_id" => "Laurentides"],
        ["name"=> "Barkmere", "region_id" => "Laurentides"],
        ["name"=> "Blainville", "region_id" => "Laurentides"],
        ["name"=> "Bois-des-Filion", "region_id" => "Laurentides"],
        ["name"=> "Boisbriand", "region_id" => "Laurentides"],
        ["name"=> "Brownsburg-Chatham", "region_id" => "Laurentides"],
        ["name"=> "Deux-Montagnes", "region_id" => "Laurentides"],
        ["name"=> "Estérel", "region_id" => "Laurentides"],
        ["name"=> "Lachute", "region_id" => "Laurentides"],
        ["name"=> "Lorraine", "region_id" => "Laurentides"],
        ["name"=> "Mirabel (Québec)", "region_id" => "Laurentides"],
        ["name"=> "Mont-Laurier", "region_id" => "Laurentides"],
        ["name"=> "Mont-Tremblant", "region_id" => "Laurentides"],
        ["name"=> "Prévost", "region_id" => "Laurentides"],
        ["name"=> "Rivière-Rouge", "region_id" => "Laurentides"],
        ["name"=> "Rosemère", "region_id" => "Laurentides"],
        ["name"=> "Sainte-Adèle", "region_id" => "Laurentides"],
        ["name"=> "Sainte-Agathe-des-Monts", "region_id" => "Laurentides"],
        ["name"=> "Sainte-Anne-des-Plaines", "region_id" => "Laurentides"],
        ["name"=> "Saint-Eustache", "region_id" => "Laurentides"],
        ["name"=> "Saint-Jérôme", "region_id" => "Laurentides"],
        ["name"=> "Sainte-Marguerite-du-Lac-Masson", "region_id" => "Laurentides"],
        ["name"=> "Sainte-Marthe-sur-le-Lac", "region_id" => "Laurentides"],
        ["name"=> "Saint-Sauveur", "region_id" => "Laurentides"],
        ["name"=> "Sainte-Sophie", "region_id" => "Laurentides"],
        ["name"=> "Sainte-Thérèse", "region_id" => "Laurentides"],
        ["name"=> "Laval", "region_id" => "Laval"],
        ["name"=> "La Tuque", "region_id" => "Mauricie"],
        ["name"=> "Louiseville", "region_id" => "Mauricie"],
        ["name"=> "Saint-Tite", "region_id" => "Mauricie"],
        ["name"=> "Shawinigan", "region_id" => "Mauricie"],
        ["name"=> "Trois-Rivières", "region_id" => "Mauricie"],
        ["name"=> "La Tuque", "region_id" => "Mauricie"],
        ["name"=> "Acton Vale","region_id" => "Montérégie"],
        ["name"=> "Beauharnois","region_id" => "Montérégie"],
        ["name"=> "Belœil","region_id" => "Montérégie"],
        ["name"=> "Boucherville","region_id" => "Montérégie"],
        ["name"=> "Lac-Brome","region_id" => "Montérégie"],
        ["name"=> "Brossard","region_id" => "Montérégie"],
        ["name"=> "Candiac","region_id" => "Montérégie"],
        ["name"=> "Carignan","region_id" => "Montérégie"],
        ["name"=> "Chambly","region_id" => "Montérégie"],
        ["name"=> "Châteauguay","region_id" => "Montérégie"],
        ["name"=> "Contrecœur","region_id" => "Montérégie"],
        ["name"=> "Coteau-du-Lac","region_id" => "Montérégie"],
        ["name"=> "Cowansville","region_id" => "Montérégie"],
        ["name"=> "Dunham","region_id" => "Montérégie"],
        ["name"=> "Farnham","region_id" => "Montérégie"],
        ["name"=> "Granby","region_id" => "Montérégie"],
        ["name"=> "Hudson","region_id" => "Montérégie"],
        ["name"=> "Huntingdon","region_id" => "Montérégie"],
        ["name"=> "L'Île-Cadieux","region_id" => "Montérégie"],
        ["name"=> "La Prairie","region_id" => "Montérégie"],
        ["name"=> "Léry","region_id" => "Montérégie"],
        ["name"=> "L'Île-Perrot","region_id" => "Montérégie"],
        ["name"=> "Longueuil","region_id" => "Montérégie"],
        ["name"=> "Marieville","region_id" => "Montérégie"],
        ["name"=> "Mercier","region_id" => "Montérégie"],
        ["name"=> "Mont-Saint-Hilaire","region_id" => "Montérégie"],
        ["name"=> "Notre-Dame-de-l'Île-Perrot","region_id" => "Montérégie"],
        ["name"=> "Otterburn Park","region_id" => "Montérégie"],
        ["name"=> "Pincourt","region_id" => "Montérégie"],
        ["name"=> "La Prairie","region_id" => "Montérégie"],
        ["name"=> "Richelieu","region_id" => "Montérégie"],
        ["name"=> "Saint-Amable","region_id" => "Montérégie"],
        ["name"=> "Saint-Basile-le-Grand","region_id" => "Montérégie"],
        ["name"=> "Saint-Bruno-de-Montarville","region_id" => "Montérégie"],
        ["name"=> "Sainte-Catherine","region_id" => "Montérégie"],
        ["name"=> "Saint-Césaire","region_id" => "Montérégie"],
        ["name"=> "Saint-Constant","region_id" => "Montérégie"],
        ["name"=> "Saint-Hyacinthe","region_id" => "Montérégie"],
        ["name"=> "Saint-Isidore","region_id" => "Montérégie"],
        ["name"=> "Saint-Jean-sur-Richelieu","region_id" => "Montérégie"],
        ["name"=> "Saint-Joseph-de-Sorel","region_id" => "Montérégie"],
        ["name"=> "Sainte-Julie","region_id" => "Montérégie"],
        ["name"=> "Saint-Lambert","region_id" => "Montérégie"],
        ["name"=> "Saint-Lazare","region_id" => "Montérégie"],
        ["name"=> "Saint-Ours","region_id" => "Montérégie"],
        ["name"=> "Saint-Pie","region_id" => "Montérégie"],
        ["name"=> "Saint-Rémi","region_id" => "Montérégie"],
        ["name"=> "Salaberry-de-Valleyfield","region_id" => "Montérégie"],
        ["name"=> "Sorel-Tracy","region_id" => "Montérégie"],
        ["name"=> "Sutton","region_id" => "Montérégie"],
        ["name"=> "Varennes","region_id" => "Montérégie"],
        ["name"=> "Vaudreuil-Dorion","region_id" => "Montérégie"],
        ["name"=> "Baie-d'Urfé","region_id" => "Montréal"],
        ["name"=> "Beaconsfield","region_id" => "Montréal"],
        ["name"=> "Côte-Saint-Luc","region_id" => "Montréal"],
        ["name"=> "Dollard-des-Ormeaux","region_id" => "Montréal"],
        ["name"=> "Dorval","region_id" => "Montréal"],
        ["name"=> "Hampstead","region_id" => "Montréal"],
        ["name"=> "L'Île-Dorval","region_id" => "Montréal"],
        ["name"=> "L'Île-Perrot","region_id" => "Montréal"],
        ["name"=> "Montréal","region_id" => "Montréal"],
        ["name"=> "Montréal-Est","region_id" => "Montréal"],
        ["name"=> "Montréal-Ouest","region_id" => "Montréal"],
        ["name"=> "Mont-Royal","region_id" => "Montréal"],
        ["name"=> "Pointe-Claire","region_id" => "Montréal"],
        ["name"=> "Sainte-Anne-de-Bellevue","region_id" => "Montréal"],
        ["name"=> "Chapais","region_id" => "Nord-du-Québec"],
        ["name"=> "Chibougamau","region_id" => "Nord-du-Québec"],
        ["name"=> "Lebel-sur-Quévillon","region_id" => "Nord-du-Québec"],
        ["name"=> "Matagami","region_id" => "Nord-du-Québec"],
        ["name"=> "Schefferville","region_id" => "Nord-du-Québec"],
        ["name"=> "Gatineau","region_id" => "Outaouais"],
        ["name"=> "Gracefield","region_id" => "Outaouais"],
        ["name"=> "Maniwaki","region_id" => "Outaouais"],
        ["name"=> "Thurso","region_id" => "Outaouais"],
        ["name"=> "Alma","region_id" => "Saguenay–Lac-Saint-Jean"],
        ["name"=> "Desbiens","region_id" => "Saguenay–Lac-Saint-Jean"],
        ["name"=> "Dolbeau-Mistassini","region_id" => "Saguenay–Lac-Saint-Jean"],
        ["name"=> "Métabetchouan–Lac-à-la-Croix","region_id" => "Saguenay–Lac-Saint-Jean"],
        ["name"=> "Normandin","region_id" => "Saguenay–Lac-Saint-Jean"],
        ["name"=> "Roberval","region_id" => "Saguenay–Lac-Saint-Jean"],
        ["name"=> "Saguenay","region_id" => "Saguenay–Lac-Saint-Jean"],
        ["name"=> "Saint-Félicien","region_id" => "Saguenay–Lac-Saint-Jean"],
    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->cities as $key => $value) {
            $city = $value;
            $region = \App\Models\Region::where('name','like',$city['region_id'])->select('id')->first();
            if($region){
                $city['region_id'] = $region->id;
                $city['slug'] = Str::of($city['name'])->slug("_");

                \App\Models\City::updateOrCreate($city);
            }
        }
    }
}
